Numpy

In [ ]:
import numpy as np
arr=np.array([20,40])
print(arr)

[20 40]


In [ ]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
arr = np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
arr = np.arange(1,21)
print(arr.reshape(5,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


In [ ]:
arr = np.linspace(1, 10, 5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.full((3, 5), 17)
print(arr)

[[17 17 17 17 17]
 [17 17 17 17 17]
 [17 17 17 17 17]]


In [ ]:
arr = np.array([[20, 40, 60],[80, 100, 120],[140, 160, 180]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(3, 3)
2
9
int64
[[ 20  80 140]
 [ 40 100 160]
 [ 60 120 180]]


In [ ]:
arr = np.array([
    [[10, 20, 30],
     [40, 50, 60]],

    [[70, 80, 90],
     [100, 110, 120]]
])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr[0])
print(arr[1])
print(arr[0][1])
print(arr[1][0][0])

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
3
(2, 2, 3)
12
[[10 20 30]
 [40 50 60]]
[[ 70  80  90]
 [100 110 120]]
[40 50 60]
70


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(3, 2)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]


In [ ]:
import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0:2,1:3])
print(arr[1,:])
print(arr[:,2])

[[20 30]
 [50 60]]
[40 50 60]
[30 60 90]


In [ ]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

[[1 2 3]
 [4 5 6]]
[10 11 12]
[[ 1  4]
 [ 7 10]]


In [ ]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Floor Division: [5 5 6]
Modulus: [0 0 0]
Power: [100 400 900]


In [ ]:
import numpy as np
arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)
print("\nSquare Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
print("\nExponential:", np.exp(arr))
print("\nNatural Log:", np.log(arr))
print("Log Base 10:", np.log10(arr))
print("\nSine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Tangent:", np.tan(arr))
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
print("Ceiling:", np.ceil(decimal))
print("Floor:", np.floor(decimal))

Original Array: [ 1  4  9 16 25]

Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube: [    1    64   729  4096 15625]

Absolute Value: [ 5 10 15 20 25]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Natural Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log Base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [ ]:
import numpy as np
marks = np.array([75, 82, 90, 68, 95, 88, 79])
print("Original Array:", marks)
print("Sorted Array:", np.sort(marks))
print("\nSum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Range:", np.ptp(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Index of Maximum:", np.argmax(marks))
print("Index of Minimum:", np.argmin(marks))
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27
Standard Deviation: 8.633111388421788
Variance: 74.53061224489797
Index of Maximum: 4
Index of Minimum: 3
25th Percentile: 77.0
50th Percentile: 82.0
75th Percentile: 89.0


In [ ]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.randint(1,11,5))
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))
print(np.random.normal(50,10,5))
print(np.random.uniform(10,20,5))
print(np.random.binomial(1,0.5))
print(np.random.binomial(10,0.7))
print(np.random.poisson(4,5))
print(np.random.exponential(2,5))

0.4841298905084773
[0.61959087 0.64941179 0.91004131 0.74501172 0.5675924 ]
[ 9  4  4  9 10]
ML
[52.43150277 30.6545529  46.82883119 32.49434841 49.82647261]
[16.36242465 16.71354132 14.35666101 13.3953659  17.74819666]
0
4
[5 4 8 3 4]
[1.38188557 1.64762507 2.50079835 2.26548154 4.66322511]


Scalars, vectors, matrices & tensors

In [ ]:
scalar = np.array(5)
vector = np.array([2, 5, 1])
matrix = np.array([[1, 2], [3, 4]])
tensor = np.ones((3, 2, 2))
for name, arr in [('scalar', scalar), ('vector', vector),
                  ('matrix', matrix), ('tensor', tensor)]:
    print(f'{name:7s} ndim={arr.ndim}  shape={arr.shape}')

scalar  ndim=0  shape=()
vector  ndim=1  shape=(3,)
matrix  ndim=2  shape=(2, 2)
tensor  ndim=3  shape=(3, 2, 2)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 0, 1])
print('a . b  (dot)   :', np.dot(a, b))
print('a x b  (cross) :', np.cross(a, b))

a . b  (dot)   : 7
a x b  (cross) : [ 2 11 -8]


In [ ]:
import numpy as np
import numpy.linalg as la

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('L2 norm  ||a||_2 :', la.norm(a))
print('L1 norm  ||a||_1 :', la.norm(a, 1))
print('Linf norm        :', la.norm(a, np.inf))

def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

print('cosine(a, b)     :', round(cosine(a, b), 3))

L2 norm  ||a||_2 : 3.7416573867739413
L1 norm  ||a||_1 : 6.0
Linf norm        : 3.0
cosine(a, b)     : 0.975


In [ ]:
A = np.array([[2., 1.],
              [1., 3.]])
B = np.array([[1., 0.],
              [4., 2.]])

print('A @ B (matrix multiply):\n', A @ B)
print('A.T   (transpose):\n', A.T)
print('inverse(A):\n', la.inv(A))
print('trace(A) = sum of diagonal:', np.trace(A))

A @ B (matrix multiply):
 [[ 6.  2.]
 [13.  6.]]
A.T   (transpose):
 [[2. 1.]
 [1. 3.]]
inverse(A):
 [[ 0.6 -0.2]
 [-0.2  0.4]]
trace(A) = sum of diagonal: 5.0


In [ ]:
I = np.eye(2)
print('Identity I:\n', I)
print('A @ inv(A) == I ?', np.allclose(A @ la.inv(A), I))
print('A symmetric?', np.allclose(A, A.T))
# Orthogonal: Q.T @ Q == I (a pure rotation/reflection)
theta = np.radians(30)
Q = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
print('Q orthogonal?', np.allclose(Q.T @ Q, I))

Identity I:
 [[1. 0.]
 [0. 1.]]
A @ inv(A) == I ? True
A symmetric? True
Q orthogonal? True


In [ ]:
square = np.array([[0, 1, 1, 0],
                   [0, 0, 1, 1]], dtype=float)
S = np.array([[1.5, 0.0],
              [0.0, 0.5]])
t = np.radians(30)
R = np.array([[np.cos(t), -np.sin(t)],
              [np.sin(t),  np.cos(t)]])

scaled  = S @ square
rotated = R @ square
print('Rotated corners:\n', rotated)

Rotated corners:
 [[ 0.         0.8660254  0.3660254 -0.5      ]
 [ 0.         0.5        1.3660254  0.8660254]]


In [ ]:
def close_loop(pts):
    return np.hstack([pts, pts[:, :1]])

fig, ax = plt.subplots(figsize=(5, 5))
ax.plot(*close_loop(square),  marker='o', label='original')
ax.plot(*close_loop(scaled),  marker='o', label='scaled')
ax.plot(*close_loop(rotated), marker='o', label='rotated 30 deg')
ax.axhline(0, color='gray', lw=0.5); ax.axvline(0, color='gray', lw=0.5)
ax.set_aspect('equal'); ax.legend(); ax.set_title('Linear transformations')
plt.show()

NameError: name 'plt' is not defined

In [ ]:
x=17
x//=3
print(x)

5


In [ ]:
import numpy as np
T = np.arange(12).reshape(3, 4)
print('T:\n', T)

# 1. ndim and shape
# YOUR CODE HERE
print(T.ndim)
print(T.shape)
# 2. T + T
# YOUR CODE HERE
print(T+T)
# 3. Transpose (print .T.shape) and reshape to (2, 6)
# YOUR CODE HERE
print(T.T.shape)
print(T.T.reshape(2,6))

T:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
(4, 3)
[[ 0  4  8  1  5  9]
 [ 2  6 10  3  7 11]]


In [ ]:
import numpy.linalg as la
pairs = [
    (np.array([1, 0, 1]), np.array([1, 0, 1])),    # pair 1
    (np.array([1, 2, 3]), np.array([3, 2, 1])),    # pair 2
    (np.array([2, 0, 0]), np.array([0, 5, 0])),    # pair 3
]

for i, (u, v) in enumerate(pairs, start=1):
    # 1. L1 and L2 norm of u
    # 2. cosine similarity of u and v
    # YOUR CODE HERE
    print(la.norm(u))
    print(la.norm(u,1))
    print(np.dot(u, v) / (la.norm(u) * la.norm(v)))
    pass

# 3. Most similar pair = ?   (write your answer here)
print("pair 2 is most similar")

1.4142135623730951
2.0
0.9999999999999998
3.7416573867739413
6.0
0.7142857142857143
2.0
2.0
0.0
pair 2 is most similar


In [ ]:
A = np.array([[2., 0.],
              [0., 3.]])

vals, vecs = la.eig(A)     # vals = eigenvalues, vecs columns = eigenvectors
print('Eigenvalues  (lambda):', vals)
print('Eigenvectors (columns):\n', vecs)

Eigenvalues  (lambda): [2. 3.]
Eigenvectors (columns):
 [[1. 0.]
 [0. 1.]]


In [ ]:
for i in range(len(vals)):
    v = vecs[:, i]                 # i-th eigenvector
    lhs = A @ v                    # A v
    rhs = vals[i] * v              # lambda v
    print(f'lambda={vals[i]:.1f}  A v == lambda v ?', np.allclose(lhs, rhs))

lambda=2.0  A v == lambda v ? True
lambda=3.0  A v == lambda v ? True


In [ ]:
A = np.array([[ 2.,  1., -1.],
              [-3., -1.,  2.],
              [-2.,  1.,  2.]])
b = np.array([8., -11., -3.])

x = la.solve(A, b)
print('Solution x:', x)                    # [2, 3, -1]
print('Rank of A :', la.matrix_rank(A))     # 3 -> full rank
print('Full rank -> a unique solution exists')

Solution x: [ 2.  3. -1.]
Rank of A : 3
Full rank -> a unique solution exists


In [ ]:
D = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [5., 7., 9.]])
print('Rank of D:', la.matrix_rank(D), '-> < 3, so rows are dependent')

Rank of D: 2 -> < 3, so rows are dependent


In [ ]:
king  = np.array([0.8, 0.6, 0.1, 0.2])
queen = np.array([0.7, 0.7, 0.1, 0.3])
apple = np.array([0.1, 0.0, 0.9, 0.8])

print('cosine(king, queen):', round(cosine(king, queen), 3))   # high
print('cosine(king, apple):', round(cosine(king, apple), 3))   # low

cosine(king, queen): 0.986
cosine(king, apple): 0.267
